# Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y git sudo

RUN apt-get install -y git python3 python3-pip

RUN git clone https://github.com/NightnHawk/snake.git

WORKDIR ./snake

RUN pip install -r requirements.txt