version: '3'
services:
 build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: echo "Building..."
 test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest
 deploy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: echo "Deploying..."