# Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/NightnHawk/snake.git

WORKDIR ./snake

RUN head -n -2 ./tests/gui/test_gui.py > temp.py && mv temp.py ./tests/gui/test_gui.py

RUN pip install -r requirements.txt